server:
  port: 3000
  origin: "*"
  credentials: true
logging:
  dir: "../logs"
  format: "dev"
db:
  host: "localhost"
  username: "hemat_rasa"
  password: ""
  database: "hemat_rasa"
  port: 5432
auth:
  jwtSecret: "SUPER_SECRET_KEY_FOR_JWT_32_CHARS_MINIMUM"
  jwtExpiresIn: "1d"
